CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS announcements (id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text, title TEXT NOT NULL, body TEXT NOT NULL, date TIMESTAMPTZ, type TEXT, status TEXT DEFAULT 'Active', created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS applications (id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text, application_id TEXT UNIQUE NOT NULL, status TEXT DEFAULT 'SUBMITTED', family_head_name TEXT NOT NULL, mobile TEXT, email TEXT, family_name TEXT NOT NULL, address TEXT, city TEXT, district TEXT, state TEXT, pincode TEXT, gotra TEXT, native_place TEXT, village TEXT, members_data JSONB NOT NULL DEFAULT '[]', submitted_date TIMESTAMPTZ, admin_remarks TEXT, reviewed_date TIMESTAMPTZ, resulting_family_id TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS events (id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text, title TEXT NOT NULL, slug TEXT, banner_url TEXT, description TEXT, date DATE NOT NULL, start_time TEXT, end_time TEXT, venue TEXT NOT NULL, map_location TEXT, organizer TEXT, contact TEXT, registration_open TIMESTAMPTZ, registration_close TIMESTAMPTZ, fee NUMERIC(12,2) DEFAULT 0, capacity INTEGER, rules TEXT, terms TEXT, status TEXT DEFAULT 'DRAFT', created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS families (id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text, family_id TEXT UNIQUE, family_name TEXT NOT NULL, head_name TEXT NOT NULL, status TEXT DEFAULT 'PENDING', address TEXT, city TEXT, district TEXT, state TEXT, pincode TEXT, native_place TEXT, village TEXT, gotra TEXT, contact_number TEXT, email TEXT, registration_date TIMESTAMPTZ, member_count INTEGER DEFAULT 0, application_id TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS family_members (id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text, family_id TEXT NOT NULL, membership_id TEXT UNIQUE, name TEXT NOT NULL, relationship TEXT NOT NULL, gender TEXT, dob DATE, mobile TEXT, email TEXT, education TEXT, occupation TEXT, address TEXT, photo_url TEXT, status TEXT DEFAULT 'PENDING', linked_student_id TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS student_applications (id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text, application_id TEXT UNIQUE NOT NULL, status TEXT DEFAULT 'SUBMITTED', student_name TEXT NOT NULL, mobile TEXT NOT NULL, email TEXT, dob DATE, gender TEXT, course TEXT, institution TEXT, academic_year TEXT, guardian_name TEXT, guardian_mobile TEXT, address TEXT, city TEXT, district TEXT, state TEXT, pincode TEXT, photo_url TEXT, submitted_date TIMESTAMPTZ, admin_remarks TEXT, reviewed_date TIMESTAMPTZ, resulting_student_id TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS students (id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text, student_id TEXT UNIQUE, student_name TEXT NOT NULL, status TEXT DEFAULT 'PENDING', mobile TEXT, email TEXT, dob DATE, gender TEXT, course TEXT, institution TEXT, academic_year TEXT, guardian_name TEXT, guardian_mobile TEXT, address TEXT, city TEXT, district TEXT, state TEXT, pincode TEXT, photo_url TEXT, registration_date TIMESTAMPTZ, application_id TEXT, linked_family_id TEXT, linked_membership_id TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS event_registrations (id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text, registration_id TEXT UNIQUE NOT NULL, event_id TEXT NOT NULL, event_title TEXT, family_id TEXT, member_ids JSONB NOT NULL DEFAULT '[]', member_names JSONB NOT NULL DEFAULT '[]', count INTEGER DEFAULT 0, fee_per_member NUMERIC(12,2) DEFAULT 0, total_fee NUMERIC(12,2) DEFAULT 0, payment_status TEXT DEFAULT 'PENDING', transaction_id TEXT, status TEXT DEFAULT 'REGISTERED', registered_by_id TEXT, registered_date TIMESTAMPTZ, registrant_name TEXT, registrant_email TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS transactions (id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text, transaction_id TEXT UNIQUE NOT NULL, type TEXT NOT NULL, amount NUMERIC(12,2) NOT NULL, payment_method TEXT, payment_status TEXT DEFAULT 'PENDING', family_id TEXT, member_id TEXT, event_id TEXT, reference_id TEXT, date TIMESTAMPTZ, remarks TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS notifications (id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text, title TEXT NOT NULL, message TEXT NOT NULL, type TEXT NOT NULL, recipient_family_id TEXT, read BOOLEAN NOT NULL DEFAULT FALSE, date TIMESTAMPTZ, deep_link TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS rules (id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text, section_number INTEGER, title_en TEXT NOT NULL, title_hi TEXT NOT NULL, content_en TEXT NOT NULL, content_hi TEXT NOT NULL, status TEXT DEFAULT 'Active', created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS samitis (id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text, name TEXT NOT NULL, description TEXT, formed_date DATE, status TEXT DEFAULT 'Active', created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS samiti_members (id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text, samiti_id TEXT NOT NULL, name TEXT NOT NULL, position TEXT, mobile TEXT, email TEXT, status TEXT DEFAULT 'Active', created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS feedback (id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text, feedback_id TEXT UNIQUE, member_name TEXT NOT NULL, family_id TEXT, email TEXT, feedback_type TEXT, subject TEXT, message TEXT, attachment_url TEXT, questions JSONB NOT NULL DEFAULT '[]', rating INTEGER, status TEXT DEFAULT 'Submitted', reply TEXT, replied_date TIMESTAMPTZ, replied_by_id TEXT, internal_note TEXT, archived BOOLEAN NOT NULL DEFAULT FALSE, submitted_date TIMESTAMPTZ, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS transfer_requests (id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text, request_id TEXT UNIQUE NOT NULL, request_type TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'PENDING', reason TEXT, source_student_id TEXT, source_membership_id TEXT, source_family_id TEXT, target_family_id TEXT, requester_id TEXT, admin_remarks TEXT, approved_by_id TEXT, approved_date TIMESTAMPTZ, resulting_membership_id TEXT, old_family_id TEXT, new_family_id TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS users (id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text, email TEXT UNIQUE, full_name TEXT, role TEXT DEFAULT 'user', password_hash TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());

CREATE INDEX IF NOT EXISTS applications_lookup_idx ON applications (application_id, mobile);
CREATE INDEX IF NOT EXISTS events_status_date_idx ON events (status, date DESC);
CREATE INDEX IF NOT EXISTS family_members_family_idx ON family_members (family_id);
CREATE INDEX IF NOT EXISTS notifications_recipient_idx ON notifications (recipient_family_id, date DESC);
CREATE INDEX IF NOT EXISTS transactions_family_idx ON transactions (family_id, date DESC);