BEGIN;

DELETE FROM rules;

INSERT INTO rules (section_number, title_en, title_hi, content_en, content_hi, status) VALUES
(1, 'Unity and Brotherhood', '🤝 एकता एवं भाईचारा', 'The first objective of the organization will be to connect all families of the community and strengthen mutual brotherhood.', 'संगठन का पहला उद्देश्य समाज के सभी परिवारों को जोड़ना और आपसी भाईचारा मजबूत करना होगा।', 'Active'),
(2, 'Equality and Respect', '⚖️ समानता एवं सम्मान', 'Every member will receive equal respect and equal opportunity. There will be no discrimination based on economic status, position, region, family, or any other basis.', 'हर सदस्य को समान सम्मान और समान अवसर मिलेगा। आर्थिक स्थिति, पद, क्षेत्र, परिवार या किसी अन्य आधार पर भेदभाव नहीं होगा।', 'Active'),
(3, 'Differences of Opinion, Not Differences of Heart', '🗣️ मतभेद हों, मनभेद नहीं', 'Differences of opinion are natural, but personal disputes, insults, or bitterness will have no place in the organization.', 'विचारों में अंतर स्वाभाविक है, लेकिन व्यक्तिगत विवाद, अपमान या कटुता को संगठन में स्थान नहीं दिया जाएगा।', 'Active'),
(4, 'Collective Decisions', '👥 सामूहिक निर्णय', 'Important decisions will be made through discussion, suggestions, and collective consent, not by any one individual.', 'महत्वपूर्ण निर्णय किसी एक व्यक्ति द्वारा नहीं, बल्कि चर्चा, सुझाव और सामूहिक सहमति से लिए जाएंगे।', 'Active'),
(5, 'The Organization Is Greater Than Any Individual', '🏛️ संगठन व्यक्ति से बड़ा', 'The organization will not belong to any individual, family, or particular group. A position is a responsibility, not a privilege.', 'संगठन किसी व्यक्ति, परिवार या गुट विशेष का नहीं होगा। पद सम्मान नहीं, जिम्मेदारी माना जाएगा।', 'Active'),
(6, 'Opportunities in Leadership', '🔄 नेतृत्व में अवसर', 'Responsibilities will change from time to time and new members will be given opportunities to lead, so that the organization continues to grow stronger.', 'समय-समय पर जिम्मेदारियों में परिवर्तन और नए सदस्यों को नेतृत्व का अवसर दिया जाएगा, ताकि संगठन निरंतर मजबूत होता रहे।', 'Active'),
(7, 'Women and Youth Participation', '👩‍🦱👨‍🎓 महिला एवं युवा सहभागिता', 'Women and youth will be given active participation and responsibilities in the activities and decision-making process of the organization.', 'महिलाओं और युवाओं को संगठन की गतिविधियों एवं निर्णय प्रक्रिया में सक्रिय भागीदारी और जिम्मेदारी दी जाएगी।', 'Active'),
(8, 'Financial Transparency', '💰 वित्तीय पारदर्शिता', 'Proper records of the organization’s income and expenditure will be maintained. Wherever possible, program budgets and expense details will be kept transparent.', 'संगठन की आय-व्यय का उचित रिकॉर्ड रखा जाएगा। कार्यक्रमों के लिए यथासंभव पूर्व-बजट और खर्च का विवरण पारदर्शी रखा जाएगा।', 'Active'),
(9, 'Distance from Personal and Political Interests', '🚫 व्यक्तिगत एवं राजनीतिक स्वार्थ से दूरी', 'The organization platform will not be used for personal gain, factional interests, or political promotion.', 'संगठन के मंच का उपयोग व्यक्तिगत लाभ, गुटीय हित या राजनीतिक प्रचार के लिए नहीं किया जाएगा।', 'Active'),
(10, 'No Rumors or Misleading Information', '📢 अफवाह एवं भ्रामक जानकारी नहीं', 'Unverified news, rumors, allegations against any person, or misleading information will not be shared on the organization platform.', 'बिना पुष्टि की गई खबर, अफवाह, किसी व्यक्ति पर आरोप या भ्रामक जानकारी संगठन के मंच पर साझा नहीं की जाएगी।', 'Active'),
(11, 'Privacy of Personal Information', '🔐 व्यक्तिगत जानकारी की गोपनीयता', 'Members’ mobile numbers, addresses, family information, and other private details will not be made public or shared without permission.', 'सदस्यों के मोबाइल नंबर, पता, परिवार की जानकारी और अन्य निजी विवरण बिना अनुमति के सार्वजनिक या साझा नहीं किए जाएंगे।', 'Active'),
(12, 'Support for Those in Need', '❤️ जरूरतमंदों का सहयोग', 'The organization will strive to provide organized social support, wherever possible, to families, students, and members facing difficult circumstances.', 'जरूरतमंद परिवारों, विद्यार्थियों और संकट की स्थिति में सदस्यों को यथासंभव व्यवस्थित सामाजिक सहयोग उपलब्ध कराने का प्रयास किया जाएगा।', 'Active'),
(13, 'Priority for Education and Employment', '🎓 शिक्षा एवं रोजगार को प्राथमिकता', 'Initiatives related to education, careers, employment, business, skills, and guidance for students and youth will be encouraged.', 'विद्यार्थियों और युवाओं के लिए शिक्षा, करियर, रोजगार, व्यवसाय, कौशल एवं मार्गदर्शन से संबंधित पहल को प्रोत्साहित किया जाएगा।', 'Active'),
(14, 'Joint Social and Cultural Events', '🎉 संयुक्त सामाजिक एवं सांस्कृतिक आयोजन', 'Family and cultural programs will be organized with maximum unity and collective participation across the community.', 'समाज के पारिवारिक एवं सांस्कृतिक कार्यक्रमों को अधिक से अधिक एकता और सामूहिक सहभागिता के साथ आयोजित करने का प्रयास किया जाएगा।', 'Active'),
(15, 'Progress, Advancement, and Welfare', '🌱 प्रगति, उन्नति एवं कल्याण', 'Every initiative of the organization should support the progress of families, the advancement of youth, and the collective welfare of the community.', 'संगठन की प्रत्येक पहल का उद्देश्य समाज के परिवारों की प्रगति, युवाओं की उन्नति और समाज के सामूहिक कल्याण की दिशा में होना चाहिए।', 'Active');

COMMIT;