import type * as Models from "../generated/prisma/client.js";
import { Prisma } from "../generated/prisma/client.js";

// Complete database rows for unit tests: every column at a neutral value, then
// the overrides. One builder per model (generated from prisma/schema.prisma).
const AT = new Date("2026-01-01T00:00:00Z");

export const announcementRow = (overrides: Partial<Models.Announcement> = {}): Models.Announcement => ({
  id: "announcement-1",
  title: "title",
  body: "body",
  date: null,
  type: null,
  status: null,
  createdAt: AT,
  updatedAt: AT,
  titleHi: null,
  bodyHi: null,
  ...overrides,
});

export const applicationRow = (overrides: Partial<Models.Application> = {}): Models.Application => ({
  id: "application-1",
  applicationId: "applicationId",
  status: null,
  familyHeadName: "familyHeadName",
  mobile: null,
  mobileDigits: null,
  email: null,
  familyName: "familyName",
  address: null,
  city: null,
  district: null,
  state: null,
  pincode: null,
  gotra: null,
  nativePlace: null,
  village: null,
  membersData: null,
  submittedDate: null,
  adminRemarks: null,
  reviewedDate: null,
  resultingFamilyId: null,
  createdAt: AT,
  updatedAt: AT,
  ...overrides,
});

export const eventRegistrationRow = (overrides: Partial<Models.EventRegistration> = {}): Models.EventRegistration => ({
  id: "eventregistration-1",
  registrationId: "registrationId",
  eventId: "eventId",
  eventTitle: null,
  familyId: null,
  memberIds: null,
  memberNames: null,
  count: null,
  feePerMember: null,
  totalFee: null,
  paymentStatus: null,
  transactionId: null,
  status: null,
  registeredById: null,
  registeredDate: null,
  registrantName: null,
  registrantEmail: null,
  createdAt: AT,
  updatedAt: AT,
  ...overrides,
});

export const eventRow = (overrides: Partial<Models.Event> = {}): Models.Event => ({
  id: "event-1",
  title: "title",
  slug: null,
  bannerUrl: null,
  description: null,
  date: AT,
  startTime: null,
  endTime: null,
  venue: "venue",
  mapLocation: null,
  organizer: null,
  contact: null,
  registrationOpen: null,
  registrationClose: null,
  fee: null,
  capacity: null,
  rules: null,
  terms: null,
  status: null,
  createdAt: AT,
  updatedAt: AT,
  titleHi: null,
  descriptionHi: null,
  ...overrides,
});

export const familyRow = (overrides: Partial<Models.Family> = {}): Models.Family => ({
  id: "family-1",
  familyId: null,
  familyName: null,
  headName: null,
  status: null,
  address: null,
  city: null,
  district: null,
  state: null,
  pincode: null,
  nativePlace: null,
  village: null,
  gotra: null,
  contactNumber: null,
  contactDigits: null,
  email: null,
  registrationDate: null,
  memberCount: null,
  applicationId: null,
  createdAt: AT,
  updatedAt: AT,
  ...overrides,
});

export const familyMemberRow = (overrides: Partial<Models.FamilyMember> = {}): Models.FamilyMember => ({
  id: "familymember-1",
  familyId: "familyId",
  membershipId: null,
  name: "name",
  relationship: "relationship",
  gender: null,
  dob: null,
  mobile: null,
  mobileDigits: null,
  email: null,
  education: null,
  occupation: null,
  address: null,
  photoUrl: null,
  status: null,
  linkedStudentId: null,
  createdAt: AT,
  updatedAt: AT,
  ...overrides,
});

export const feedbackRow = (overrides: Partial<Models.Feedback> = {}): Models.Feedback => ({
  id: "feedback-1",
  feedbackId: null,
  memberName: "memberName",
  familyId: null,
  email: null,
  feedbackType: null,
  subject: null,
  message: null,
  attachmentUrl: null,
  questions: null,
  rating: null,
  status: null,
  reply: null,
  repliedDate: null,
  repliedById: null,
  internalNote: null,
  archived: false,
  submittedDate: null,
  createdAt: AT,
  updatedAt: AT,
  ...overrides,
});

export const notificationRow = (overrides: Partial<Models.Notification> = {}): Models.Notification => ({
  id: "notification-1",
  title: "title",
  message: "message",
  type: "type",
  recipientFamilyId: null,
  read: false,
  date: null,
  deepLink: null,
  createdAt: AT,
  updatedAt: AT,
  ...overrides,
});

export const principleRow = (overrides: Partial<Models.Principle> = {}): Models.Principle => ({
  id: "principle-1",
  sectionNumber: null,
  titleEn: "titleEn",
  titleHi: "titleHi",
  contentEn: "contentEn",
  contentHi: "contentHi",
  status: "Active",
  createdAt: AT,
  updatedAt: AT,
  ...overrides,
});

export const ruleRow = (overrides: Partial<Models.Rule> = {}): Models.Rule => ({
  id: "rule-1",
  sectionNumber: null,
  titleEn: "titleEn",
  titleHi: "titleHi",
  contentEn: "contentEn",
  contentHi: "contentHi",
  status: null,
  createdAt: AT,
  updatedAt: AT,
  ...overrides,
});

export const samitiMemberRow = (overrides: Partial<Models.SamitiMember> = {}): Models.SamitiMember => ({
  id: "samitimember-1",
  samitiId: "samitiId",
  name: "name",
  position: null,
  mobile: null,
  email: null,
  status: null,
  createdAt: AT,
  updatedAt: AT,
  ...overrides,
});

export const samitiRow = (overrides: Partial<Models.Samiti> = {}): Models.Samiti => ({
  id: "samiti-1",
  name: "name",
  description: null,
  formedDate: null,
  status: null,
  createdAt: AT,
  updatedAt: AT,
  ...overrides,
});

export const studentApplicationRow = (overrides: Partial<Models.StudentApplication> = {}): Models.StudentApplication => ({
  id: "studentapplication-1",
  applicationId: "applicationId",
  status: null,
  studentName: "studentName",
  mobile: "mobile",
  mobileDigits: null,
  email: null,
  dob: null,
  gender: null,
  course: null,
  institution: null,
  academicYear: null,
  guardianName: null,
  guardianMobile: null,
  address: null,
  city: null,
  district: null,
  state: null,
  pincode: null,
  photoUrl: null,
  submittedDate: null,
  adminRemarks: null,
  reviewedDate: null,
  resultingStudentId: null,
  createdAt: AT,
  updatedAt: AT,
  fatherName: null,
  ...overrides,
});

export const studentRow = (overrides: Partial<Models.Student> = {}): Models.Student => ({
  id: "student-1",
  studentId: null,
  studentName: "studentName",
  status: null,
  mobile: null,
  mobileDigits: null,
  email: null,
  dob: null,
  gender: null,
  course: null,
  institution: null,
  academicYear: null,
  guardianName: null,
  guardianMobile: null,
  address: null,
  city: null,
  district: null,
  state: null,
  pincode: null,
  photoUrl: null,
  registrationDate: null,
  applicationId: null,
  linkedFamilyId: null,
  linkedMembershipId: null,
  createdAt: AT,
  updatedAt: AT,
  fatherName: null,
  ...overrides,
});

export const transactionRow = (overrides: Partial<Models.Transaction> = {}): Models.Transaction => ({
  id: "transaction-1",
  transactionId: "transactionId",
  type: "type",
  amount: new Prisma.Decimal(0),
  paymentMethod: null,
  paymentStatus: null,
  familyId: null,
  memberId: null,
  eventId: null,
  referenceId: null,
  date: null,
  remarks: null,
  createdAt: AT,
  updatedAt: AT,
  ...overrides,
});

export const transferRequestRow = (overrides: Partial<Models.TransferRequest> = {}): Models.TransferRequest => ({
  id: "transferrequest-1",
  requestId: "requestId",
  requestType: "requestType",
  status: "PENDING",
  reason: null,
  sourceStudentId: null,
  sourceMembershipId: null,
  sourceFamilyId: null,
  targetFamilyId: null,
  requesterId: null,
  adminRemarks: null,
  approvedById: null,
  approvedDate: null,
  resultingMembershipId: null,
  oldFamilyId: null,
  newFamilyId: null,
  createdAt: AT,
  updatedAt: AT,
  requesterName: null,
  requesterEmail: null,
  requesterMobile: null,
  targetFamilyName: null,
  requestedDate: null,
  ...overrides,
});

export const userRow = (overrides: Partial<Models.User> = {}): Models.User => ({
  id: "user-1",
  email: null,
  fullName: null,
  role: null,
  passwordHash: null,
  isVerified: true,
  status: "active",
  sessionToken: null,
  sessionExpiresAt: null,
  resetTokenHash: null,
  resetTokenExpiresAt: null,
  createdAt: AT,
  updatedAt: AT,
  phone: null,
  otpHash: null,
  otpExpiresAt: null,
  photoUrl: null,
  ...overrides,
});
